apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: graphics-app
  labels:
    app: backend
    version: v1
    team: backend-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        team: backend-cluster
    spec:
      containers:
      - name: backend
        image: ghcr.io/graphics-app/backend:IMAGE_TAG
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: NODE_ENV
          value: "staging"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: AI_SERVICE_URL
          value: "http://ai-services:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: graphics-app
  labels:
    app: backend
    team: backend-cluster
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP 