apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: graphics-app
  labels:
    app: frontend
    version: v1
    team: frontend-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        team: frontend-cluster
    spec:
      containers:
      - name: frontend
        image: ghcr.io/graphics-app/frontend:IMAGE_TAG
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: NODE_ENV
          value: "staging"
        - name: REACT_APP_API_URL
          value: "http://backend:8000"
        - name: REACT_APP_AI_SERVICE_URL
          value: "http://ai-services:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: graphics-app
  labels:
    app: frontend
    team: frontend-cluster
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP 